#ifndef TOKENS
#define TOKENS

#define STRING_HAVING_5TH_ELEMENT_AS_a 1
#define STRING_HAVING_LAST_LETTER_AS_p 2
#define STRING_ab 3
#define STRING_HAVING_ONECAP_ONENUM_ONESPECIAL 4
#define STRING_HAVING_MY_NAME 5
#define STRING_WITH_LP 6
#define NEW_LINE_OR_TAB_OR_SPACE 7
#define INVALID_STRING 8

#endif